### ISSUE TITLE
Write tests for the server

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#15]
Test's should be written for the code that is already there as well as code that is written in the future. But to complete this issue, just adding test coverage to the existing code will do.

**Comment by regexb** [comment]
@cpjolicoeur I saw you wrote tests for the template parser using the standard testing library. What do you think about adding a 3rd party library like goconvey or testify?

**Comment by cpjolicoeur** [comment]
Your call really.  Now that I have found Looper, the only thing goconvey really gives me is the web UI - which is super nice if you want something like that, for me personally looper works good enough.  Of course, it also add's the convey syntax and some other ways to do assertions.

Testify provides a different set of niceties like asserts, mocks and is typically used in conjunction with something like the core httptest package.

I'm open to adding either, I didn't add them initially because I was just writing some quick coverage and didn't really need any features that werent already provided by the core Testing framework
